name: Flake8

on: [push]

jobs:
  build:
    name: Analyse code with Flake8
    runs-on: ubuntu-latest
    container: python:3.11-alpine
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Analysing the code with flake8
      run: |
        flake8
