name: Pylint

on: [push]

jobs:
  build:
    name: Analyse code with PyLint
    runs-on: ubuntu-latest
    container: python:3.11-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --recursive=y .
