name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set version
      run: |
        sed -i "s/^_VERSION = .*/_VERSION = '${{ github.ref_name }}'/" load.py
    - name: Create plugin artifact
      run: |
        zip RoutePlanner.zip README.md load.py
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "RoutePlanner.zip"
